### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by humanagent** [Vamsieth/farcast#1]
Hello there! I wanted to thank you for your contribution to OpenFrame. I am happy to let you know that your work has been added to the [Awesome-Open-Frame](https://github.com/open-frames/awesome-open-frames) repository. It would be great if you could update your readme with a brief description of the frame along with an image showcasing it. Adding the URL in the repository description and readme would make it easier for users to try it out. Thank you!

README
- Title
- Description
- Image or Gif in Converse or Warpcast
- Live URL

Also, here is a cool example i found from the submissions: https://github.com/rtomas/peace-frame-farcaster

**Comment by Vamsieth** [comment]
Hi, I've made the changes. pls go through them once and confirm

**Comment by humanagent** [comment]
Love it!

**Comment by humanagent** [comment]
Love it!
